// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSCategory.Data;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OSCategory.Entities.OSCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("OSCategories");
                });

            modelBuilder.Entity("OSCategory.Entities.OperationSystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OSCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("OSCategorysId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("RequiredSpace")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OSCategorysId");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("OSCategory.Entities.OperationSystemModel", b =>
                {
                    b.HasOne("OSCategory.Entities.OSCategories", "OSCategorys")
                        .WithMany("operationSystemModels")
                        .HasForeignKey("OSCategorysId");

                    b.Navigation("OSCategorys");
                });

            modelBuilder.Entity("OSCategory.Entities.OSCategories", b =>
                {
                    b.Navigation("operationSystemModels");
                });
#pragma warning restore 612, 618
        }
    }
}
